name: R-CMD-check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Notify slack success
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01MS7ECQ8Z
          status: STARTING
          color: warning
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Check for and install Git Large File Storage (LFS)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install git-lfs 
          sudo git lfs install        
      - name: Install curl
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install curl libcurl4-openssl-dev libcurl4-doc 
          sudo apt-get install libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
      - name: Check for and install Git Large File Storage (LFS)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install git-lfs 
          sudo git lfs install
      - name: Install R pkg Linux dependencies 
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install pandoc libmpfr-dev libmpfr-doc texlive-latex-recommended 
          sudo apt-get install texlive-xetex texlive-luatex pandoc-citeproc texlive-latex-extra context 
          sudo apt-get install wkhtmltopdf librsvg2-bin groff ghc nodejs python libjs-mathjax node-katex    
          
      - name: Install remotes, rcmdcheck, and all FA imports & Suggests
        run: |
          install.packages(c("remotes", "rcmdcheck", "Rmpfr"), dependencies = TRUE)
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: R CMD Check
        run: rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "error")
        shell: Rscript {0}
        env:
          _R_CHECK_FORCE_SUGGESTS_: false

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01MS7ECQ8Z
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01MS7ECQ8Z
          status: FAILED
          color: danger

